### ISSUE TITLE
Display the event date

### ISSUE THREAD

**Issue by kristinn** [rosenpin/i3-agenda#19]
I'm wondering if it wouldn't make sense to display the event date if the event doesn't occur "today"?

For instance, the next event currently in my personal calendar isn't until 22:00 tomorrow. However, the i3-agenda script outputs it as just 22:00 (omitting the date).

What is your opinion?

**Comment by fabfurnari** [comment]
Yes, at showing only the hour can be confusing. Ideally it could display like "13 Apr@22:00" or "13/04@22:00"  or maybe "Tomorrow@22:00"

**Comment by kristinn** [comment]
Yeah, I'm just going to create a very simple PR that basically just displays it as "2020-04-14@22:00". It's better than omitting the date altogether, but it's still something that can be made more beautiful if that's of an interest.

**Comment by rosenpin** [comment]
That would be nice.  
I didn't originally include it because I wanted to keep it simple, but if it only shows the date if it's not today it will still look great!
