### ISSUE TITLE
Add option to clear cache

### ISSUE THREAD

**Issue by marcospb19** [rosenpin/i3-agenda#32]
Something like `--refresh` or `--update` to prevent the function `load_cache()` of returning the event list.

This is useful after you update something in the calendar and want to force the update without setting `--cachettl` to a low value or deleting the file manually.

**Comment by rosenpin** [comment]
Seems possible, then you could for example assign the right button click on the plugin to run `i3-agenda --refresh` to force a refresh. Then the next time the widget updates it will already load the updated list
