### ISSUE TITLE
Long-lasting Focus/Highlight Color

### ISSUE THREAD

**Issue by Zackhardtoname** [rosenpin/i3-agenda#58]
![image](https://user-images.githubusercontent.com/25935197/123732390-d7e0d800-d867-11eb-814a-6f97026db29c.png)

As you can see at the bottom, my event is in red text and white background. It seems to start when the event is about to happen but it just doesn't go away even after the starting time of the event. Left and/or right clicking doesn't get rid of it. Thanks!

**Comment by rosenpin** [comment]
this is most likely the problematic line 

https://github.com/rosenpin/i3-agenda/blob/aebb1644f4610b15698def46b832893b2b98a3cf/i3_agenda/__init__.py#L162


It should not include the case where the event is in the past
