### ISSUE TITLE
scrolling on the bar module navigate the events

### ISSUE THREAD

**Issue by notdodo** [rosenpin/i3-agenda#63]
Hi!

Is it possible to enable the scrolling feature on the module (on polybar) to navigate past and future events?

**Comment by rosenpin** [comment]
Currently it's impossible to do this.  
A relatively easy way to do this will be to  
1. add support for an "skip" flag for the script, where the skip will represent the number of events to skip, for example `./i3-agenda -... --skip 1` will fetch the events[1] (the second closest event)
2. make a utility script that will keep the skip number in a file. Something like
```
#!/bin/bash
file=/tmp/i3-agenda-skip.tmp
skip=$(cat $file)
skip+=1
echo $skip >> $file
```
3. make polybar refresh the events on scroll
```
[module/agenda]
    ...
    type = custom/script
    exec = i3-agenda -c ~/.google_credentials.json -ttl 30
    enable-scroll = true
    scroll-up = i3-agenda -c ~/.google_credentials.json --update
    interval = 1 # you can instead refresh the bar manually on scroll up instead of having a low interval. See here for more info https://github.com/polybar/polybar/issues/563
```


## TODO:
- [ ] add support for skip flag in i3-agenda
