### ISSUE TITLE
Refactoring 

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/i3-agenda#84]
- [x] Move constant (numbers/strings) values to consts
- [x] Rename main file from __init__ to main/i3-agenda.py
- [ ] Separate functions with 3+ indentation levels or over 15 lines 
- [x] Clean up event.py file (choose logical separation between methods/file functions)

**Comment by matclab** [comment]
A quick browsing does not show me function needing refactoring because of complexity. 
@rosenpin, do you have some in mind ?

**Comment by matclab** [comment]
Please tell me if you think something else shall be done.

Before taking maintenance, I'd also like to add more testing (I quickly began `human_delta` which chocked:
```
    def test_human_delta():
        assert human_delta(dt.timedelta(0)) == "0m"
        assert human_delta(dt.timedelta(minutes=1)) == "1m"
>       assert human_delta(dt.timedelta(hours=1)) == "1h"
E       AssertionError: assert '0m' == '1h'
E         - 1h
E         + 0m
```
).

I'll open a new PR based upon #89 for tests.

**Comment by rosenpin** [comment]
Great find  
I'll look into the PR and comment on everything once I get a chance (hopefully next few days)  
Thanks!

**Comment by rosenpin** [comment]
> A quick browsing does not show me function needing refactoring because of complexity. @rosenpin, do you have some in mind ?  

As a general rule, as mentioned in the issue description

> Separate functions with 3+ indentation levels or over 15 lines

Some example I found include  
* get_credentials
* get_callendar_ids
* get_all_events
* get_events_from_cache
* get_string
* get_future_events
