### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/i3-agenda#86]
I no longer use i3 (moved to mac) so I no longer use and update this plugin.  
Looking for someone to help maintain this repo  
I can continue doing code reviews but it will be difficult for me to test this plugin as a menu bar  
For more details or if you are interested feel free to email me or comment on this issue

**Comment by matclab** [comment]
I may be interested, as I use this valuable piece of software daily. However I know I have little available time (life is short).

Perhaps I may try to submit a PR for #84 and #87, and if I succeed it will be a good indicator  I may be able to maintain this for some time.

**Comment by rosenpin** [comment]
@matclab Sounds good

**Comment by matclab** [comment]
> Perhaps I may try to submit a PR for #84 and #87, and if I succeed it will be a good indicator I may be able to maintain this for some time.

Goal reached (and more quickly than I expected) :popcorn:

**Comment by rosenpin** [comment]
I invited you as a collaborator 🎉
